---
title: "Programa de Prevención y Control de Arbovirosis | 2056 | Victoria de Durango"
format: 
  dashboard:
    nav-buttons: [twitter, github, facebook]
    logo: https://framework-gb.cdn.gob.mx/gobmx/img/logo_blanco.svg
theme: custom.scss
---

```{r setup}
library(sf)
library(magrittr)
library(mapgl)
load("/Users/fdzul/Documents/geocoding_mx_2026_dengue/4.RData/dengue_mx_2026.RData")
source("~/Library/CloudStorage/Dropbox/r_developments/r_dashboards/netlify/1.2.persisten_dengue_transmission_2026/persistent_dengue_transmission_10_durango/mp_heatmap.R")
source("~/Library/CloudStorage/Dropbox/r_developments/r_dashboards/netlify/1.2.persisten_dengue_transmission_2026/persistent_dengue_transmission_10_durango/mp_transmission_chains.R")
library(fishualize)

source("~/Library/CloudStorage/Dropbox/r_developments/r_dashboards/netlify/1.2.persisten_dengue_transmission_2026/persistent_dengue_transmission_10_durango/mp_dengue_cases.R")
```


# [**Cadenas de Transmisión**]{style="font-size:2pt"}

::: panel-tabset

### [**Hermosillo**]{style="color:#990000"}

::::::::::::::::::::: responsive-grid

<div class="columna">
<div class="column-header"> Distribución de Casos </div>

::: grid-card

```{r distribucion_hermosillo2,echo=FALSE}
z |>
    dplyr::filter(IDE_EDA_ANO <= 12 | IDE_EDA_ANO >= 65) |>
    dplyr::mutate(onset = FEC_INI_SIGNOS_SINT) |>
    dplyr::select(ANO, long, lat, onset) |>
    dplyr::mutate(x = long,
                  y = lat) |>
    sf::st_as_sf(coords = c("x", "y"),
                 crs = 4326) |>
    mp_dengue_cases(yrs = 2026,
                    locality = "Hermosillo",
                    cve_edo = "26")


```
:::

</div><div class="columna">
<div class="column-header"> Cadenas de Transmisión </div>

::: grid-card

```{r chains_hermosillo2,echo=FALSE}
z |>
    dplyr::filter(IDE_EDA_ANO <= 12 | IDE_EDA_ANO >= 65) |>
    dplyr::mutate(onset = FEC_INI_SIGNOS_SINT) |>
    dplyr::select(ANO, long, lat, onset) |>
    dplyr::mutate(x = long,
                  y = lat) |>
    sf::st_as_sf(coords = c("x", "y"),
                 crs = 4326) |>
    mp_transmission_chains(
                           yrs = 2026,
                           locality = "Hermosillo",
                           cve_edo = "26")

```
:::

</div><div class="columna">
<div class="column-header"> Mapa de Calor </div>

::: grid-card

```{r heatmap_hermosillo2,echo=FALSE}
z |>
    dplyr::filter(IDE_EDA_ANO <= 12 | IDE_EDA_ANO >= 65) |>
    dplyr::mutate(onset = FEC_INI_SIGNOS_SINT) |>
    dplyr::select(ANO, long, lat, onset) |>
    dplyr::mutate(x = long,
                  y = lat) |>
    sf::st_as_sf(coords = c("x", "y"),
                 crs = 4326) |>
  mp_heatmap(yrs = 2026,
           cve_edo = "26",
           locality = "Hermosillo")


```
:::

</div>

::::::::::::::::::::

:::



